DROP TABLE IF EXISTS time_entry_tags;
DROP TABLE IF EXISTS timer_tags;
DROP TABLE IF EXISTS task_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS time_entries;
DROP TABLE IF EXISTS timers;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS projects;
